# Generated by Django 4.0.2 on 2022-02-11 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workdaymanagement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workday',
            name='time_in',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='workday',
            name='time_out',
            field=models.DateTimeField(),
        ),
    ]
