# Generated by Django 4.0.2 on 2022-02-12 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workdaymanagement', '0003_alter_workday_time_in_alter_workday_time_out'),
    ]

    operations = [
        migrations.AddField(
            model_name='workday',
            name='hours_worked',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
