# Generated by Django 4.0.2 on 2022-02-12 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workdaymanagement', '0008_alter_workday_hours_worked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workday',
            name='hours_worked',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
