# Generated by Django 4.0.2 on 2022-02-12 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workdaymanagement', '0009_alter_workday_hours_worked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workday',
            name='hours_worked',
        ),
    ]
