# Generated by Django 4.0.2 on 2022-02-13 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workdaymanagement', '0012_alter_workday_hours_worked'),
    ]

    operations = [
        migrations.AddField(
            model_name='workday',
            name='total_payroll',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
