# Generated by Django 4.0.2 on 2022-02-13 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workdaymanagement', '0014_alter_workday_total_payroll'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workday',
            name='payroll',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
