# Generated by Django 4.0.2 on 2022-02-11 02:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0002_alter_profile_doc_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='doc_id',
        ),
    ]
